spring.application.name=Utown
spring.jpa.show-sql=true

# Active Spring profile
spring.profiles.active=local

# Enable SQL parameter binding logs (for debugging Hibernate SQL queries)
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# SQL initialization settings
spring.sql.init.data-locations=classpath:data.sql
spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=true
