spring.application.name=Utown
spring.jpa.show-sql=true

# ACTIVE SPRING PROFILE
spring.profiles.active=local

# Database Setting
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${URL}
spring.datasource.username=${USERNAME}
spring.datasource.password=${PASSWORD}

# JWT Configuration
jwt.access-secret=${JWT_ACCESS_SECRET}
jwt.refresh-secret=${JWT_REFRESH_SECRET}
jwt.access-expiration-ms=${JWT_ACCESS_EXPIRATION_MS}
jwt.refresh-expiration-ms=${JWT_REFRESH_EXPIRATION_MS}

# Enable SQL parameter binding logs (for debugging Hibernate SQL queries)
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true

# SQL initialization settings
spring.sql.init.data-locations=classpath:data.sql
spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=true



aws.region=ap-southeast-2
aws.s3.bucket=selcadarmor
aws.credentials.access-key=LOCAL_ACCESS_KEY
aws.credentials.secret-key=LOCAL_SECRET_KEY