spring.application.name=Utown
spring.profiles.active=production

# JWT Configuration
jwt.access-secret=${JWT_ACCESS_SECRET}
jwt.refresh-secret=${JWT_REFRESH_SECRET}
jwt.access-expiration-ms=${JWT_ACCESS_EXPIRATION_MS}
jwt.refresh-expiration-ms=${JWT_REFRESH_EXPIRATION_MS}


# AWS  S3 settings
aws.region=${AWS_REGION}
aws.s3-bucket=${AWS_S3_BUCKET}
aws.credentials.access-key=${AWS_ACCESS_KEY}
aws.credentials.secret-key=${AWS_SECRET_KEY}
aws.endpoint=https://s3.ap-southeast-2.amazonaws.com
aws.publicBaseUrl=https://s3.ap-southeast-2.amazonaws.com/selcadarmor

#Logging
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.com.example.Utown=DEBUG
logging.level.org.springframework=DEBUG
logging.level.com.example=DEBUG


logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %level [%thread] %logger{10} : %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} - %level [%thread] %logger{10} : %msg%n

logging.file.name=logs/Utown.log
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=30


# Flyway settings
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Enable SQL parameter binding logs (for debugging Hibernate SQL queries)
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
