# Change username and password to match your local database
# Then add this file to .gitignore to avoid sharing sensitive credentials

# Database settings
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${URL}
spring.datasource.username=${USERNAME}
spring.datasource.password=${PASSWORD}


