INSERT INTO roles (name)
SELECT * FROM (SELECT 'ROLE_ADMIN') AS tmp
WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name = 'ROLE_ADMIN');

INSERT INTO roles (name)
SELECT * FROM (SELECT 'ROLE_CLIENT') AS tmp
WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name = 'ROLE_CLIENT');

INSERT INTO roles (name)
SELECT * FROM (SELECT 'ROLE_RESTAURANT_ADMIN') AS tmp
WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name = 'ROLE_RESTAURANT_ADMIN');
